import { Achievement } from '../types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_word',
    title: 'First Step',
    description: 'Add your first vocabulary word to FlashLearn.',
    icon: 'Sparkles',
    isUnlocked: true,
    progress: 100,
    unlockedAt: new Date().toISOString(),
  },
  {
    id: 'streak_3',
    title: 'Streak Apprentice',
    description: 'Maintain a 3-day review streak.',
    icon: 'Flame',
    isUnlocked: false,
    progress: 33,
  },
  {
    id: 'streak_7',
    title: 'Consistency Master',
    description: 'Review vocabulary 7 consecutive days in a row.',
    icon: 'Award',
    isUnlocked: false,
    progress: 14,
  },
  {
    id: 'words_25',
    title: 'Word Collector',
    description: 'Have at least 25 words in your library.',
    icon: 'BookOpen',
    isUnlocked: false,
    progress: 50,
  },
  {
    id: 'learned_5',
    title: 'Memory Novice',
    description: 'Advance 5 words into the Learned stage.',
    icon: 'CheckCircle2',
    isUnlocked: false,
    progress: 20,
  },
  {
    id: 'learned_20',
    title: 'Polyglot Scholar',
    description: 'Master 20 words into long-term Learned memory.',
    icon: 'Trophy',
    isUnlocked: false,
    progress: 5,
  },
  {
    id: 'quiz_ace',
    title: 'Quiz Ace',
    description: 'Answer 5 quiz questions correctly without any mistakes.',
    icon: 'Target',
    isUnlocked: false,
    progress: 40,
  },
  {
    id: 'difficulty_crusher',
    title: 'Challenge Master',
    description: 'Successfully conquer a HARD or VERY HARD word.',
    icon: 'Zap',
    isUnlocked: false,
    progress: 0,
  },
];
